apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: "glusterfs-distributed"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://${ICP_PROXY_NODE_IP}:${ICP_HEKETI_SERVICE_PORT}"
  volumetype: "replicate:3"
reclaimPolicy: Delete
